import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// Suppress TS error for side-effect CSS import when no global type declarations are present
// @ts-ignore: Cannot find module or type declarations for side-effect import of './globals.css'
import "./globals.css";
import Providers from "@/providers/Providers";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/ui/core/ThemeProvider/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MediHaven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <Toaster richColors position="top-center" />
            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
